#!/bin/bash

if [[ -z "${PYTHON_EXEC}" ]]; then
  echo "PYTHON_EXEC being set to 'python'"
  export PYTHON_EXEC="python"
fi

if [[ -z "${GYM_POP_SOURCE}" ]]; then
  echo "GYM_POP_SOURCE being set to 'output_pd.csv'"
  export GYM_POP_SOURCE="output_pd.csv"
fi

# stolen from stack overflow
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

(
cd $SCRIPT_DIR
$PYTHON_EXEC parse_output.py "${GYM_POP_SOURCE}"
)
